include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    curly_braces_in_flow_control_structures: ignore
  exclude:
    - lib/*.g.dart
    - lib/generated/*.dart
    - lib/generated/l10n/*.dart
    - lib/main.widgetbook.dart